### ISSUE TITLE
House configuration portal

### ISSUE THREAD

**Issue by akm3** [Philter-Non-Profit/Aura#2]
As a HM, I need to be able to add and remove Guests (and their cell#) from a list, so that only current house residents receive communications

Acceptance Criteria
1) Quick and easy to create, update, remove Guest's cell phone numbers from the active list to be communicated to
2) Only HM can access portal
3) Accessible via web page that also works well on cell phone
4) Includes Name and Cell Number, no additional Guest data required

**Comment by quattro004** [comment]
Added and removed regularly yes but I think the re-add would an exception. Families come and go frequently and there's an approval process.
