### ISSUE TITLE
Determine Architecture/Technology

### ISSUE THREAD

**Issue by akm3** [Philter-Non-Profit/Aura#5]
As a Developer, I need architectural and technology decisions made so that I can start on the MVP

Acceptance Criteria
1) As low/no cost as possible
2) Must support SMS
3) Must be configured by a web portal
4) Must have a listener that can accept texts from house manager to blast out
5) Must not reveal house manager personal cell phone
6) Determine branching strategy
7) Determine deployment strategy/pipelines?
8) Determine Test / Unit Test straetgy

Is this Twilio? Is this some other service? Where hosted? How much? Solve my problems

**Comment by adamskt** [comment]
Azure Service Bus seems to give us a bunch of features we need without rolling our own message queue: https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-overview#concepts
Delayed delivery: https://learn.microsoft.com/en-us/azure/service-bus-messaging/message-sequencing#scheduled-messages

I think a relational store for messages here is the wrong way to go as performance will decrease linearly over time/usage.

Twilio seems like the best game in town for SMS, Azure has an offering but it seems pretty expensive to start up: https://learn.microsoft.com/en-us/azure/communication-services/concepts/sms-pricing
