### ISSUE TITLE
Licensing / Read Me / Etc

### ISSUE THREAD

**Issue by akm3** [Philter-Non-Profit/Aura#6]
As a Philter Contributor, I need to define our open source/licensing/agreements so I know Philter values are being adhered to

Acceptance Criteria
1) Define our read mes so others can come on and collaborate
2) Define our license agreement so Philter is protected and commercial use is regulated
3) Generally make it easy for non Philter developers to join and contribute meaningfully

**Comment by adamskt** [comment]
Closed by #7
