### ISSUE TITLE
Setup Azure infrastructure

### ISSUE THREAD

**Issue by adamskt** [Philter-Non-Profit/Aura#9]
- [x] Create Azure account for Philter
- [x] Add resource group (US West 2?)
- [x] Add SQL DB
- [x] Add Azure AD (Microsoft Entra ID)
- [x] Add App Service Plan
- [x] Add app service to run the basic app in dev (later to become prod)
- [ ] Build pipeline deploy using Github actions?

**Comment by GrantErickson** [comment]
What service will actually send the messages? All of these cost dollars as far as I know. The email thing is broken for Verizon now.

**Comment by adamskt** [comment]
See https://github.com/Philter-Non-Profit/Aura/issues/5#issuecomment-1433343998
